version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: mycontainer-01
    image: myimage:1.05
    ports:
    - "8082:8080"
    restart: always
    volumes:
    - myvol:/test
    - /tetra:/meta
    networks:
    - mynet
volumes:
  myvol:
networks:
  mynet:
    driver: bridge
